apiVersion: v1
kind: Pod
metadata:
  name: toilet-go
spec:
  containers:
    - name: python-api
      image: docker.io/l33gn21/python-api:latest  # Python API 이미지
      ports:
        - containerPort: 54090  # Python API가 사용하는 포트 
    - name: spring-api
      image: docker.io/l33gn21/spring-api:latest  # Spring API 이미지
      ports:
        - containerPort: 54080  # Spring Boot가 사용하는 포트
