name: Deploy Python and Spring Servers

# 수동 실행을 위해 workflow_dispatch 추가
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build Python Docker image
      - name: Build Python image
        run: |
          docker build -t my-dockerhub-username/python-api:latest ./dataApi
          docker push my-dockerhub-username/python-api:latest

      # 4. Build Spring Docker image
      - name: Build Spring image
        run: |
          docker build -t my-dockerhub-username/spring-api:latest ./springApi
          docker push my-dockerhub-username/spring-api:latest

      # 5. Deploy Python container
      - name: Deploy Python server
        run: |
          docker pull my-dockerhub-username/python-api:latest
          docker run -d --name python-server -p 8000:8000 my-dockerhub-username/python-api:latest

      # 6. Deploy Spring container
      - name: Deploy Spring server
        run: |
          docker pull my-dockerhub-username/spring-api:latest
          docker run -d --name spring-server -p 8080:8080 my-dockerhub-username/spring-api:latest
